---
- debug: var=out.stdout_lines

# ***********************************************************
# 
# ***********************************************************

- name: Install Ansible

# ***********************************************************
# 
# ***********************************************************

- name: Install Terraform

# ***********************************************************
# 
# ***********************************************************

- name: Install Cockpit

# ***********************************************************
# 
# ***********************************************************

- name: Install doctl


# ***********************************************************
# 
# ***********************************************************

- name: Install npm with nvm


# ***********************************************************
# 
# ***********************************************************

- name: Install Wrangler

Once you've installed nvm and configured your system to use the nvm managed node install, run:

npm i @cloudflare/wrangler -g

https://github.com/coding-to-music/coding-to-music.github.io/issues/295


# ***********************************************************
# 
# ***********************************************************

- name: Verify git connection

ssh -vT git@github.com


# ***********************************************************
# 
# ***********************************************************

- name: Install Rust

https://www.rust-lang.org/tools/install

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh